### ISSUE TITLE
Incorrect pro file?

### ISSUE THREAD

**Issue by NemoinGLA** [pablocael/qtoffscreenoglrender#1]
Hi there
In the pro file, it seems to need some extra files like OffscreenRenderer.cpp&.h and  mainwindow.cpp&.h. Could u update these files as well?

**Comment by pablocael** [comment]
Thanks for reporting. Will take a look.

**Comment by pablocael** [comment]
Sorry for the delay. Those sources included in the .pro file were not being used. I have removed from the .pro file now. Thanks for reporting. Changed in this commit: [9a90827](https://github.com/pablocael/qtoffscreenoglrender/commit/9a90827103a3ee3304e606ac8ead6b7b0f9e63be)
